mode: swav

data:
  datasets_path: /home/lmk22/datasets
  train_dataset: imagenet
  batch_size: 512 # For each device, so the effective batch size is batch_size * num_devices
  num_workers: 64 # For each device, so the effective number of workers is num_workers * num_devices
  prefetch_factor: 1
  pin_memory: false
  drop_last: true
  global_views:
    num: 2
    crop_scale:
      - 0.14
      - 1.0
    crop_ratio:
      - 0.75
      - 1.3333333333333333
    color_jitter: true
    gaussian_blur: true
    horizontal_flip: true
    crop_size: 224
  local_views:
    num: 4
    crop_scale:
      - 0.05
      - 0.14
    crop_ratio:
      - 0.75
      - 1.3333333333333333
    color_jitter: true
    gaussian_blur: true
    horizontal_flip: true
    crop_size: 96

  normalize:
    mean:
      - 0.485
      - 0.456
      - 0.406
    std:
      - 0.229
      - 0.224
      - 0.225
  separate_val_subset:
    use: false
    size: 0.1

meta:
  model_name: resnet50
  checkpoint: false
  projection_dim: 128
  pretrained_weights: null # Path to the pretrained weights file. Set to null if you don't want to load pretrained weights.
  save_every: 0 # Set to 0 if you don't want to save intermediate checkpoints during training

optimization:
  ipe_scale: 1.0
  lr:
    - 0.00001
    - 0.6
    - 0.0048
  weight_decay:
    - 1e-6
    - 1e-6
  num_epochs: 100
  warmup_epochs: 10
  optimizer: lars
  temperature: 0.1
  sinkhorn_epsilon: 0.05
  sinkhorn_iterations: 3
  num_prototypes: 3000
  queue_length: 3840
  queue_start_epoch: 1
