from torch.distributed.nn.functional import all_gather
from time import strftime, localtime
import torch.distributed as dist
import matplotlib.pyplot as plt
import torch.nn as nn
import torch
import json
import math
import os

def write_on_log(text, output_path):
    if not is_main_process():
        return

    time = strftime("%Y-%m-%d %H:%M:%S - ", localtime())
    mode = "w" if not os.path.exists(os.path.join(output_path, "log.txt")) else "a"
    with open(os.path.join(output_path, "log.txt"), mode) as file:
        file.write(time + text + "\n")

def write_on_csv(output_path, epoch, iteration, loss, lr, wd, ema="-"):
    if not is_main_process():
        return
    
    file_path = os.path.join(output_path, "log.csv")
    file_exists = os.path.isfile(file_path)

    with open(file_path, "a") as csv_file:
        if not file_exists:
            csv_file.write("timestamp,epoch,iteration,loss,lr,wd,ema\n")

        csv_file.write(f"{strftime('%Y-%m-%d %H:%M:%S', localtime())},{epoch},{iteration},{loss},{lr},{wd},{ema}\n")

def is_distributed():
    return int(os.environ.get("WORLD_SIZE", "1")) > 1

def is_main_process():
    return int(os.environ.get("RANK", "0")) == 0

def plot_fig(x, x_name, y, y_name, fig_name, output_path):
    if not is_main_process():
        return

    plt.figure()
    plt.plot(x, y)
    plt.xlabel(x_name)
    plt.ylabel(y_name)
    plt.title(fig_name)

    os.makedirs(output_path + "figs", exist_ok=True)

    plt.savefig(os.path.join(output_path + "figs", f"{fig_name}.png"))
    plt.close()

def save_json(data, output_path, file_name):
    if not is_main_process():
        return

    with open(os.path.join(output_path, f"{file_name}.json"), "w") as f:
        json.dump(data, f, indent=4)

def concat_all_gather(tensor):
    if not dist.is_available() or not dist.is_initialized():
        return tensor

    return torch.cat(all_gather(tensor), dim=0)

def recreate_csv_log(output_folder, last_epoch):
    if not is_main_process():
        return

    csv_path = os.path.join(output_folder, "log.csv")
    with open(csv_path, "r") as f:
        lines = f.readlines()

        new_lines = lines[:1] + [line for line in lines[1:] if int(line.split(",")[1]) <= last_epoch]

        with open(csv_path, "w") as f:
            f.writelines(new_lines)

def get_last_epoch(output_folder):
    last_epoch_path = os.path.join(output_folder, "last_epoch.json")
    if not os.path.exists(last_epoch_path):
        return 0
    
    with open(last_epoch_path, "r") as f:
        last_epoch_data = json.load(f)
    
    return last_epoch_data.get("last_epoch", 0)

def load_last_values(output_folder, last_epoch, test=False, val=False):
    lr_values = []
    wd_values = []
    ema_values = []
    train_loss = []
    test_top1 = []
    test_top5 = []
    test_loss = []
    val_top1 = []
    val_top5 = []
    val_loss = []

    csv_path = os.path.join(output_folder, "log.csv")
    with open(csv_path, "r") as f:
        lines = f.readlines()[1:]
    
    for line in lines:
        epoch = line.split(",")[1]
        lr = line.split(",")[4]
        wd = line.split(",")[5]
        ema = line.split(",")[6].strip()
        if int(epoch) <= last_epoch:
            lr_values.append(float(lr))
            wd_values.append(float(wd))

            if ema != "-":
                ema_values.append(float(ema))
    
    training_info_json = json.load(open(os.path.join(output_folder, "training_info.json"), "r"))
    train_loss.extend(training_info_json.get("train_loss", []))

    if test:
        test_info_json = json.load(open(os.path.join(output_folder, "testing_info.json"), "r"))
        test_top1.extend(test_info_json.get("test_top1", []))
        test_top5.extend(test_info_json.get("test_top5", []))
        test_loss.extend(test_info_json.get("test_loss", []))

        if val:
            val_info_json = json.load(open(os.path.join(output_folder, "validation_info.json"), "r"))
            val_top1.extend(val_info_json.get("val_top1", []))
            val_top5.extend(val_info_json.get("val_top5", []))
            val_loss.extend(val_info_json.get("val_loss", []))

            return lr_values, wd_values, ema_values, train_loss, test_top1, test_top5, test_loss, val_top1, val_top5, val_loss

        else:
            return lr_values, wd_values, ema_values, train_loss, test_top1, test_top5, test_loss

    return lr_values, wd_values, ema_values, train_loss

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor

'''
Fill the input tensor with values drawn from a truncated normal distribution.
'''
def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (torch.Tensor, float, float, float, float) -> torch.Tensor
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)

def repeat_interleave_batch(x, B, repeat):
    N = len(x) // B
    x = torch.cat([
        torch.cat([x[i*B:(i+1)*B] for _ in range(repeat)], dim=0)
        for i in range(N)
    ], dim=0)
    return x

class AllReduceSum(torch.autograd.Function):

    @staticmethod
    def forward(ctx, x):
        if (
            dist.is_available()
            and dist.is_initialized()
            and (dist.get_world_size() > 1)
        ):
            x = x.contiguous()
            dist.all_reduce(x)
        return x

    @staticmethod
    def backward(ctx, grads):
        return grads

_NORM_MODULES = (
    nn.BatchNorm1d,
    nn.BatchNorm2d,
    nn.BatchNorm3d,
    nn.SyncBatchNorm,
    nn.LayerNorm,
    nn.GroupNorm,
    nn.InstanceNorm1d,
    nn.InstanceNorm2d,
    nn.InstanceNorm3d,
)


def make_param_groups(
    model,
    weight_decay,
    decay_bias=True,
    decay_norm=True,
    adapt_bias=False,
    adapt_norm=False,
    lr=None,
    fix_lr=False,
):
    param_groups = []

    for module_name, module in model.named_modules():
        is_norm_module = isinstance(module, _NORM_MODULES)

        for param_name, param in module.named_parameters(recurse=False):
            if not param.requires_grad:
                continue

            is_bias = param_name == "bias"
            is_norm = is_norm_module

            use_decay = True

            if is_bias and not decay_bias:
                use_decay = False

            if is_norm and not decay_norm:
                use_decay = False

            group = {
                "params": [param],
                "weight_decay": weight_decay if use_decay else 0.0,
                "weight_decay_exclude": not use_decay,

                "is_bias": is_bias,
                "is_norm": is_norm,

                "decay_bias": decay_bias,
                "decay_norm": decay_norm,

                "adapt_bias": adapt_bias, # do not adapt bias by default for sgd and adamw
                "adapt_norm": adapt_norm, # do not adapt norm by default  for sgd and adamw

                "fix_lr": fix_lr,
            }

            if lr is not None:
                group["lr"] = lr
                group["initial_lr"] = lr

            param_groups.append(group)

    return param_groups
